### PR TITLE
Add celsius option

### PR DESCRIPTION
**Pull request by jamescarruthers**
Add celsius as an option for those outside the United States :)

### CODE REVIEW

**Comment by mantonakakis1** [comment]
Hi James, I just committed an updated version - give it a try and let me know if it works. I think all you should need to do is add "#define CELSIUS" to your .ino file, otherwise it should default to Fahrenheit. I haven't tested it with my car, but my Arduino code compiles, at least.

**Comment by jamescarruthers** [comment]
Fab. Works for me!

**Comment by mantonakakis1** [comment]
> Fab. Works for me!

Excellent! It was a great feature request, btw. It should hopefully lead to some expanded functionality (controlling memory usage for users of more limited microcontrollers, adding a simple dash broadcasting version, etc). Thank you!

**Comment by jamescarruthers** [comment]
Oh, just spotted a mistake. It's 5/9 not 9/5.

**Comment by mantonakakis1** [comment]
Fixed!

**Pull request closed without merging**
